src/objects/Camping_Item__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Packed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Camping Item</label>
    <nameField>
        <displayFormat>CI-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Camping Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Camping Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DB_CampingItemSelector.cls
public class DB_CampingItemSelector extends fflib_SObjectSelector { 
    public List<Schema.SObjectField> getSObjectFieldList() {
    	return new List<Schema.SObjectField> {
    		Camping_Item__c.id,
    		Camping_Item__c.name,
    		Camping_Item__c.name__c,
    		Camping_Item__c.packed__c,
    		Camping_Item__c.price__c,
    		Camping_Item__c.quantity__c
    	};
    } 
    
    public Schema.SObjectType getSObjectType() {
    	return Camping_Item__c.sObjectType;
    }    
    
    public List<Camping_Item__c> selectAll() {
    	return (List<Camping_Item__c>) Database.query(
        	newQueryFactory().toSOQL()
        );
    }
}