src/objects/Session__c.object
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session_Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SESP-{00000}</displayFormat>
        <label>Session Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestRejectDoubleBooking.cls
@isTest
public class TestRejectDoubleBooking {
    private static final User TestRunner = TEST_RunAsUserFactory.create();

	static testMethod void testSingleBooking() {
		// Arrange
		Datetime now = System.now();
		Speaker__c speaker = TEST_FakeSpeakerFactory.create(TEST_DummyInsertModeEnum.REAL);
		Session__c session = TEST_FakeSessionFactory.create(TEST_DummyInsertModeEnum.REAL);
		Session_Speaker__c sessionSpeaker = new Session_Speaker__c (session__c = session.id, speaker__c = speaker.id);
		
		// Act
		Database.SaveResult result;
        System.runAs(TestRunner) {
            Test.startTest();
            {
                result = Database.insert(sessionSpeaker, false);
            }
            Test.stopTest();
        }
		
		// Assert
		System.assert(result.isSuccesS());
	}    
}