src/objects/Session__c.object
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session_Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SESP-{00000}</displayFormat>
        <label>Session Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DB_SessionSpeakerSelector.cls
public class DB_SessionSpeakerSelector extends fflib_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
    	return new List<Schema.SObjectField> {
    		Session_Speaker__c.Session__c,
    		Session_Speaker__c.Speaker__c
    	};
    } 
    
    public Schema.SObjectType getSObjectType() {
    	return Session_Speaker__c.sObjectType;
    }
    
    public List<Session_Speaker__c> selectById(Set<Id> idSet) {
        return (List<Session_Speaker__c>) this.selectWithDetails(idSet);
    }
    
    public List<Session_Speaker__c> selectById(List<Id> idList) {
        return this.selectById(new Set<Id>(idList));
    }
    
    public List<Session_Speaker__c> selectBySpeakerId(List<Id> idList){
        return (List<Session_Speaker__c>) Database.query(
                this.prepSessionSpeakerQueryFactory().setCondition('speaker__c IN :idList').toSOQL()
        );
    }
    
    private List<Session_Speaker__c> selectWithDetails(Set<Id> idSet) {
        return (List<Session_Speaker__c>) Database.query(
                this.prepSessionSpeakerQueryFactory().setCondition('id IN :idSet').toSOQL()
        );
    }

    private fflib_QueryFactory prepSessionSpeakerQueryFactory() {
        fflib_QueryFactory sessionSpeakerQueryFactory = newQueryFactory();

		new DB_SessionSelector().configureQueryFactoryFields(sessionSpeakerQueryFactory, 'Session__c');
		new DB_SpeakerSelector().configureQueryFactoryFields(sessionSpeakerQueryFactory, 'Speaker__c');

		return sessionSpeakerQueryFactory;
    }
}