src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Session_Date__c</fullName>
        <label>Session Date</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session_Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SESP-{00000}</displayFormat>
        <label>Session Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CMA_SendConfirmationEmailStrategy.cls
public class CMA_SendConfirmationEmailStrategy extends UTIL_IfPopulatedListStrategy {
	EmailManager emailManager;
	Boolean result = true;
	
	public CMA_SendConfirmationEmailStrategy (EmailManager emailManager) {
		this.emailManager = emailManager;
	}

	public CMA_SendConfirmationEmailStrategy () {
		this(new EmailManager());
	}
	
     public void doIfPopulated(List<Object> listToCheck) {
     	for (object obj: listToCheck) {
     		Session_Speaker__c sessionSpeaker = (Session_Speaker__c) obj;
     		Speaker__c speaker = sessionSpeaker.speaker__r;
     		Session__c session = sessionSpeaker.session__r;
     		String address = speaker.email__c;
     		if (!String.isBlank(address)) {
	     		String subject = 'Speaker Confirmation';
	     		String message = 'Dear ' + speaker.first_name__c  
	     			+ ',\nYour session "' + session.name
	     			+ '" on ' + session.session_date__c 
	     			+ 'is confirmed.\n\n'
	     			+ 'Thanks for speaking at the conference!';
	     		this.result &= emailManager.send(address, subject, message);
     		}
     	}
     }
     
     public void doIfEmpty() {
     }
     
     public Boolean getResult() {
     	return this.result;
     }
}