src/objects/Speaker__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TEST_FakeSpeakerFactory.cls
@isTest
public class TEST_FakeSpeakerFactory extends TEST_SObjectFactory {
	private static Map<String, Object> defaultByKeyMap = new Map<String, Object>{
	}; 
	
	public static List<Speaker__c> createList(Speaker__c template, Integer quantity, TEST_DummyInsertModeEnum insertMode){
		MockStrategyInterface strategy = new SpeakerInQuantityStrategy(template, quantity); 
		return (List<Speaker__c>) TEST_SObjectFactory.createList(strategy, insertMode); 
	}
	
	public static Speaker__c create(TEST_DummyInsertModeEnum insertMode){
		Speaker__c template = new Speaker__c(first_name__c = 'John', last_name__c = 'Smith');
		Integer quantity = 1;
		return createList(template, quantity, insertMode)[0];
	}

	class SpeakerInQuantityStrategy extends SObjectInQuantityStrategy {
		SpeakerInQuantityStrategy(SObject template, Integer quantity) {
			super(template, quantity, 'Speaker__c ', defaultByKeyMap);
		} 
	}

/*	
	public static List<Speaker__c> createList(
			Speaker__c template, Integer quantity, List<Account> accountList, TEST_DummyInsertModeEnum insertMode
		){
		MockStrategyInterface strategy = new nSpeakersPerAccountStrategy(template, quantity, accountList); 
		return (List<Speaker__c>) TEST_SObjectFactory.createList(strategy, insertMode);
	}	  
 
	class nSpeakersPerAccountStrategy extends nSObjectPerRelatedSObjectStrategy {
		nSpeakersPerAccountStrategy(SObject template, Integer quantity, List<Account> accountList) {
			super(template, quantity, 'Speaker__c ', 'accountId', accountList, defaultByKeyMap);
		}
	}
*/	
}